### ISSUE TITLE
It does't patch the coreDNS after create fargate profile

### ISSUE THREAD

**Issue by zhaoyi0113** [terraform-module/terraform-aws-eks-fargate-profile#12]
Based on https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html, we need to patch the core dns pod  by this command:

```
kubectl patch deployment coredns \
    -n kube-system \
    --type json \
    -p='[{"op": "remove", "path": "/spec/template/metadata/annotations/eks.amazonaws.com~1compute-type"}]'
```

it seems this module doesn't patch it.

**Comment by ivankatliarchuk** [comment]
This will require to couple module with kubernetes provider. I would suggest not to do it, but instead orchestrate it with another module that explicitly just does CoreDns patch

**Comment by andrewmclagan** [comment]
Is there an end-to-end example of booting a Fargate cluster with a "normal" setup?
