### ISSUE TITLE
aws_auth configmap is over written.

### ISSUE THREAD

**Issue by RavindraSinghKhichi** [terraform-module/terraform-aws-eks-fargate-profile#5]
Hey there, 

When first time we deploy eks cluster everythings fine, cm in eks has the role for pod execution but in subsequent runs it overwrites the cm and that leaves fargate profile non functional, any help on this will be much appreciated .

Thanks!!

**Comment by ivankatliarchuk** [comment]
I will try to share own of my setup when have time
